# Site settings
title: Aniketh Girish
email: aniketh.girish@imdea.org
description: > # this means to ignore newlines until "baseurl:"
  Aniketh Girish: Final year bachelor student in Computer
  Science & Engineering at the Amrita Vishwa Vidhyapeetham.
  Interested in the Internet protocols, security, privacy, and measurement.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.anikethgirish.in" # the base hostname & protocol for your site
production_url: "https://www.anikethgirish.in"
github_username: Aniketh01
permalink: /blog/:year/:month/:title.html

twitter:
  username: __aniketh

# Google Analytics
#google_analytics_tracking_id: UA-3992453-11

sass:
  style: compressed

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
